### ISSUE TITLE
Add test case status

### ISSUE THREAD

**Issue by rajat503** [prasadtalasila/JavaAutolab#6]
- Make failure of a test case more verbose by providing description of failure.

- Give memory and runtime statistics.

**Comment by rajat503** [comment]
Compilation Error, Wrong Answer, Timeout and Accepted are now provided as status messages for each test case. Do we need the exact error log as well? Also, what would be the best way to get the memory and runtime stats?

**Comment by prasadtalasila** [comment]
If it's not time consuming to add, you may add the error log feature; otherwise, let's focus on high-priority tasks.

The memory stats can be produced by using a combination of Runtime.getruntime().totalMemory() and Runtime.getruntime().freeMemory() methods. There are caveats to use of these functions which are explained well on the [StackOverflow](http://stackoverflow.com/questions/17374743/how-can-i-get-the-memory-that-my-java-program-uses-via-javas-runtime-api?lq=1) thread. You may consult the Javadoc on the [Runtime](https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html) class.

Timing stats can be produced using System.nanoTime() method. See the [Javadoc](https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#nanoTime()) and the helpful comments on [StackOverflow thread](http://stackoverflow.com/questions/351565/system-currenttimemillis-vs-system-nanotime).

The other run-time aspect of CPU usage requires writing JNI; let us postpone the collection of CPU usage statistics to future.

**Comment by prasadtalasila** [comment]
Not high priority right now. We can look at this later.
